In [ ]:
!pip install --upgrade google-cloud-bigquery vertexai pandas streamlit pyngrok

Requirement already satisfied: google-cloud-bigquery in /usr/local/lib/python3.12/dist-packages (3.41.0)
Collecting vertexai
  Downloading vertexai-1.71.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 991.1 kB/s eta 0:00:00
Collecting streamlit
  Downloading streamlit-1.56.0-py3-none-any.whl.metadata (9.8 kB)
Collecting pyngrok
  Downloading pyngrok-8.0.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: google-api-core<3.0.0,>=2.11.1 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (2.30.3)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.47.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.5.1)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.8.2)
Requirement already satisfied: packaging>=24.2.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (26.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.9.0.post0)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.32.4)
Collecting google-cloud-aiplatform==1.71.1 (from google-cloud-aiplatform[all]==1.71.1->vertexai)
  Downloading google_cloud_aiplatform-1.71.1-py2.py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (1.27.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (5.29.6)
Collecting google-cloud-storage<3.0.0dev,>=1.32.0 (from google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai)
  Downloading google_cloud_storage-2.19.0-py2.py3-none-any.whl.metadata (9.1 kB)
Requirement already satisfied: google-cloud-resource-manager<3.0.0dev,>=1.3.3 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (1.17.0)
Requirement already satisfied: shapely<3.0.0dev in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (2.1.2)
Requirement already satisfied: pydantic<3 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (2.12.3)
Requirement already satisfied: docstring-parser<1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (0.17.0)
WARNING: google-cloud-aiplatform 1.71.1 does not provide the extra 'all'
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.46)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.19.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.74.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.80.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.71.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (4.9.1)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery) (1.8.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: grpc-google-iam-v1<1.0.0,>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-resource-manager<3.0.0dev,>=1.3.3->google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (0.14.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.6.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (0.4.2)
Downloading vertexai-1.71.1-py3-none-any.whl (7.3 kB)
Downloading google_cloud_aiplatform-1.71.1-py2.py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 21.0 MB/s eta 0:00:00
Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 53.4 MB/s eta 0:00:00
Downloading streamlit-1.56.0-py3-none-any.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 57.2 MB/s eta 0:00:00
Downloading pyngrok-8.0.0-py3-none-any.whl (24 kB)
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 51.1 MB/s eta 0:00:00
Downloading google_cloud_storage-2.19.0-py2.py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.8/131.8 kB 12.0 MB/s eta 0:00:00
Installing collected packages: pyngrok, pydeck, pandas, streamlit, google-cloud-storage, google-cloud-aiplatform, vertexai
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
  Attempting uninstall: google-cloud-storage
    Found existing installation: google-cloud-storage 3.10.1
    Uninstalling google-cloud-storage-3.10.1:
      Successfully uninstalled google-cloud-storage-3.10.1
  Attempting uninstall: google-cloud-aiplatform
    Found existing installation: google-cloud-aiplatform 1.147.0
    Uninstalling google-cloud-aiplatform-1.147.0:
      Successfully uninstalled google-cloud-aiplatform-1.147.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.2 which is incompatible.
google-adk 1.29.0 requires google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0, but you have google-cloud-aiplatform 1.71.1 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.2 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.2 which is incompatible.
db-dtypes 1.5.1 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.2 which is incompatible.
Successfully installed google-cloud-aiplatform-1.71.1 google-cloud-storage-2.19.0 pandas-3.0.2 pydeck-0.9.2 pyngrok-8.0.0 streamlit-1.56.0 vertexai-1.71.1

In [ ]:
from google.colab import auth
auth.authenticate_user()

In [ ]:
from google.cloud import bigquery
import vertexai
from vertexai.generative_models import GenerativeModel

# set your project details
PROJECT_ID = "your-project-id"  # Enter your own project id here
LOCATION = "us-central1"

# Initialize clients
bq_client = bigquery.Client(project=PROJECT_ID)
vertexai.init(project=PROJECT_ID, location=LOCATION)

# Load model
model = GenerativeModel("gemini-2.5-pro")

In [ ]:
# fetch KPIs query

kpi_query = """
select
  round(avg(burnout_score),1) as avg_burnout_score,
  round(countif(attrition_risk = 'High') * 100.0 / count(*), 1) as pct_high_attrition_risk,
  round(avg(hours_with_ai_assistance_daily),1) as avg_daily_ai_hours,
  round(avg(productivity_score),1) as avg_productivity_score,
  round(avg(ai_replaces_my_tasks_pct),1) as tasks_replaced
from my_db.workforce;

"""

kpi_df = bq_client.query(kpi_query).to_dataframe()
kpi_df

,avg_burnout_score,pct_high_attrition_risk,avg_daily_ai_hours,avg_productivity_score,tasks_replaced
0,50.1,5.7,4.2,57.5,41.2

In [ ]:
# task replaced by AI vs role

task_replacement_query = """
select job_role, round(avg(ai_replaces_my_tasks_pct),1) as task_replacement_percent
from my_db.workforce
group by job_role
order by  task_replacement_percent desc;
"""

task_replacement_df = bq_client.query(task_replacement_query).to_dataframe()
task_replacement_df

             job_role  task_replacement_percent
0    Backend Engineer                      43.5
1   Software Engineer                      43.4
2        Data Analyst                      42.6
3     Cloud Architect                      42.6
4      Data Scientist                      42.5
5   AI Ethics Officer                      42.0
6     DevOps Engineer                      42.0
7         ML Engineer                      41.9
8   Frontend Engineer                      41.6
9     Product Manager                      38.5
10      AI Researcher                      37.0
11    Prompt Engineer                      36.4

In [ ]:
# attrition risk by ai adoption

attrition_by_adoption_query = """
select ai_adoption_stage, attrition_risk,
count(*) as emp_count,
round(count(*) * 100.0/ sum(count(*)) over(partition by ai_adoption_stage),2) as percent
from my_db.workforce
group by ai_adoption_stage, attrition_risk
order by ai_adoption_stage, attrition_risk;
"""

attrition_by_adoption_df = bq_client.query(attrition_by_adoption_query).to_dataframe()
attrition_by_adoption_df

   ai_adoption_stage attrition_risk  emp_count  percent
0           AI-First           High         16     6.40
1           AI-First            Low        120    48.00
2           AI-First         Medium        114    45.60
3      Experimenting           High         20     5.59
4      Experimenting            Low        184    51.40
5      Experimenting         Medium        154    43.02
6        Integrating           High         25     5.08
7        Integrating            Low        232    47.15
8        Integrating         Medium        235    47.76
9         Optimizing           High         24     6.00
10        Optimizing            Low        188    47.00
11        Optimizing         Medium        188    47.00

In [ ]:
# fear of ai replacement

fear_of_ai_query = """
select fear_of_ai_replacement, round(count(*) * 100.0/ sum(count(*)) over (), 2) as percent
from my_db.workforce
group by fear_of_ai_replacement;

"""

fear_of_ai_df = bq_client.query(fear_of_ai_query).to_dataframe()
fear_of_ai_df

  fear_of_ai_replacement  percent
0                   High    23.87
1                    Low    34.87
2                 Medium    41.27

In [ ]:
# high attrition risk cohort

high_attrition_query = """
select industry, round(avg(years_experience),2) as avg_YoE,
round(avg(burnout_score),2) as avg_burnout,
round(avg(job_satisfaction_1_5),2) as avg_job_satisfaction
from my_db.workforce
where fear_of_ai_replacement = 'High' and attrition_risk = 'High'
group by industry
order by avg_YoE desc;

"""

high_attrition_df = bq_client.query(high_attrition_query).to_dataframe()
high_attrition_df

        industry  avg_YoE  avg_burnout  avg_job_satisfaction
0     Consulting    14.40        63.00                  2.72
1        Fintech    12.40        56.00                  2.88
2          Media    12.22        60.00                  2.88
3     E-commerce     9.85        60.46                  2.65
4     Automotive     9.14        65.00                  2.47
5           SaaS     9.00        62.67                  2.65
6         Gaming     8.88        60.75                  2.60
7     Healthtech     8.60        57.30                  2.74
8  Cybersecurity     8.33        60.78                  2.81
9         EdTech     6.43        54.29                  2.83

In [ ]:
#Convert data to text format
kpi_context = kpi_df.to_string(index = False)
task_replacement_context = task_replacement_df.to_string(index = False)
attrition_by_adoption_context = attrition_by_adoption_df.to_string(index = False)
fear_of_ai_context = fear_of_ai_df.to_string(index = False)
high_attrition_context = high_attrition_df.to_string(index = False)

In [ ]:
# generate_insights function
def generate_insights(user_question):
    prompt = f"""
    You are a senior data analyst.

    Dataset Context:
    - 1500 tech employees (2026)
    - Focus: AI adoption vs burnout, productivity, and attrition

    Key KPIs:
    {kpi_context}

    Industry Attrition Insights:
    {high_attrition_context}

    Attrition Risk vs AI Adoption Stage Insights:
    {attrition_by_adoption_context}

    Percent of tasks replaced by AI for each job role Insights:
    {task_replacement_context}

    Fear of AI replacement Insights:
    {fear_of_ai_context}


    User Question:
    {user_question}
    Give insights, risks, and recommendations based on the user question.

    Instructions:
    1. Answer in 3 - 4 sentences only.
    2. Identify key patterns and trends
    3. Explain business impact
    4. Highlight risks (burnout, attrition, overuse of AI)
    4. Provide clear, actionable recommendations
    5. Keep response structured and concise with headings
    6. Only use the provided data. Do not assume missing values
    """
    response = model.generate_content(prompt)
    return response.text

In [ ]:
user_question = input("Ask a question about the dashboard")

# call the function
response = generate_insights(user_question)

Ask a question about the dashboardHow can we prevent attrition in the automotive industry?

In [ ]:
print(response)

### **Analysis of Attrition in the Automotive Industry**

**Key Insight**
The data reveals the automotive industry is a high-risk sector, exhibiting the highest average burnout score (65.00) and the lowest average job satisfaction (2.47) compared to all other industries.

**Risks & Business Impact**
This toxic combination of severe burnout and poor satisfaction is a primary driver for high employee attrition, threatening the retention of experienced staff (avg. 9.14 YoE) and leading to significant knowledge loss and increased hiring costs.

**Recommendation**
To prevent attrition, immediately prioritize targeted initiatives to diagnose and address the root causes of burnout while implementing programs to improve job satisfaction, as these are the most critical factors identified in the data for this industry.

In [ ]:
## Streamlit app

%%writefile app.py
import streamlit as st
import base64
from google.cloud import bigquery
import vertexai
from vertexai.generative_models import GenerativeModel

# -----------------------------
# INIT
# -----------------------------
# Set your project details
PROJECT_ID = "focus-arcanum-494414-i5"
LOCATION = "us-central1"

# Initialize clients
bq_client = bigquery.Client(project=PROJECT_ID)
vertexai.init(project=PROJECT_ID, location=LOCATION)

# Load model
model = GenerativeModel("gemini-2.5-pro")

#-------- Load Data Context -------------

# fetch KPIs query
kpi_query = """
select
  round(avg(burnout_score),1) as avg_burnout_score,
  round(countif(attrition_risk = 'High') * 100.0 / count(*), 1) as pct_high_attrition_risk,
  round(avg(hours_with_ai_assistance_daily),1) as avg_daily_ai_hours,
  round(avg(productivity_score),1) as avg_productivity_score,
  round(avg(ai_replaces_my_tasks_pct),1) as tasks_replaced
from my_db.workforce;
"""

kpi_df = bq_client.query(kpi_query).to_dataframe()

#high attrition risk cohort
high_attrition_query = """
--High Attrition Risk Cohort
select industry, round(avg(years_experience),2) as avg_YoE,
round(avg(burnout_score),2) as avg_burnout,
round(avg(job_satisfaction_1_5),2) as avg_job_satisfaction
from my_db.workforce
where fear_of_ai_replacement = 'High' and attrition_risk = 'High'
group by industry
order by avg_YoE desc;

"""

high_attrition_df = bq_client.query(high_attrition_query).to_dataframe()


#attrition risk by ai adoption
attrition_by_adoption_query= """
--Attrition Risk By AI Adoption Stage
select ai_adoption_stage, attrition_risk,
count(*) as emp_count,
round(count(*) * 100.0/ sum(count(*)) over(partition by ai_adoption_stage),2) as percent
from my_db.workforce
group by ai_adoption_stage, attrition_risk
order by ai_adoption_stage, attrition_risk;

"""

attrition_by_adoption_df = bq_client.query(attrition_by_adoption_query).to_dataframe()

#tasks replaced by AI vs role
task_replacement_query = """
--task replacement % by role
select job_role, round(avg(ai_replaces_my_tasks_pct),1) as task_replacement_percent
from my_db.workforce
group by job_role
order by  task_replacement_percent desc;
"""

task_replacement_df = bq_client.query(task_replacement_query).to_dataframe()

#fear of ai replacement
fear_of_ai_query = """
select fear_of_ai_replacement, round(count(*) * 100.0/ sum(count(*)) over (), 2) as percent
from my_db.workforce
group by fear_of_ai_replacement;
"""

fear_of_ai_df = bq_client.query(fear_of_ai_query).to_dataframe()


#Convert Data to Text Context
kpi_context = kpi_df.to_string(index=False)
high_attrition_context = high_attrition_df.to_string(index=False)
attrition_by_adoption_context = attrition_by_adoption_df.to_string(index=False)
task_replacement_context =  task_replacement_df.to_string(index=False)
fear_of_ai_context = fear_of_ai_df.to_string(index=False)


# generate_insights function
def generate_insights(user_question):
    prompt = f"""
    You are a senior data analyst.

    Dataset Context:
    - 1500 employees (2026)
    - Focus: AI adoption vs burnout, productivity, and attrition

    Key KPIs:
    {kpi_context}

    Industry Attrition Insights:
    {high_attrition_context}

    Attrition Risk vs AI Adoption Stage Insights:
    {attrition_by_adoption_context}

    Percent of tasks replaced by AI for each job role Insights:
    {task_replacement_context}

    Fear of AI replacement Insights:
    {fear_of_ai_context}


    User Question:
    {user_question}

    Instructions to answer the user question:
    1. Answer straightforward in 3 - 4 sentences only
    2. Explain business impact
    3. Provide clear, actionable recommendations
    4. Keep response structured and concise with headings
    5. Only use the provided data. Do not assume missing values
    """
    response = model.generate_content(prompt)
    return response.text

#--- UI -----
st.set_page_config(layout="wide")

st.title("AI Workforce Dashboard + GenAI Insights")

# ---- LOAD DASHBOARD ----
with open("AI Workplace Attrition.pdf", "rb") as f:
    pdf_bytes = f.read()

base64_pdf = base64.b64encode(pdf_bytes).decode('utf-8')

pdf_display = f"""
<iframe src="data:application/pdf;base64,{base64_pdf}"
width="100%" height="600" type="application/pdf"></iframe>
"""

st.markdown("## Dashboard")
st.markdown(pdf_display, unsafe_allow_html=True)


# ---- QUESTION INPUT ----
st.markdown("## 🤖 Ask a question about the dashboard")

user_question = st.text_input("Enter your question:")

if st.button("Get Insights"):
    if user_question:
        st.write("### Response:")
        #from ai_workforce_attrition import generate_insights

        response = generate_insights(user_question)
        st.write(response)

Writing app.py

In [ ]:
from pyngrok import ngrok

ngrok.set_auth_token("your-auth-token")  # Enter your own auth token here

In [ ]:
!pkill -f streamlit
!streamlit run app.py &>/dev/null &

In [ ]:
public_url = ngrok.connect(8501)
print(public_url)

NgrokTunnel: "https://wannabe-geek-giddiness.ngrok-free.dev" -> "http://localhost:8501"